### ISSUE TITLE
ユニットテストの実装とCI/CD統合

### ISSUE THREAD

**Issue by skage-plusfor** [plus4/plusfor-internal-portal#34]
## 概要
GitHub Actions を使用してPush時にユニットテストが自動実行される仕組みを構築します。コードの品質とリグレッション防止のため、包括的なユニットテストスイートを実装します。

## 現在の問題
- ユニットテストが実装されていない
- コード変更時の影響範囲が把握できない
- リグレッションの検出が困難
- 品質保証のプロセスが不十分

### 1. テストフレームワーク選定・設定
- **Jest** + **React Testing Library** の導入
- TypeScript サポートの設定
- テスト環境の構築

#### フロントエンド
- **コンポーネントテスト**
  - `components/auth/*` - 認証関連コンポーネント
  - `components/ui/*` - UIコンポーネント
  - `app/*/components/*` - ページ専用コンポーネント

- **ユーティリティ関数テスト**
  - `lib/utils.ts` - ユーティリティ関数
  - `lib/auth.ts` - 認証ロジック
  - バリデーション関数

#### バックエンド
- **API ルートテスト**
  - `app/api/users/*` - ユーザー関連API
  - `app/api/admin/*` - 管理者API
  - `app/api/announcements/*` - お知らせAPI

- **データベース操作テスト**
  - Supabase クライアント操作
  - RLS ポリシーのテストMock

### 3. GitHub Actions ワークフロー
```yaml
# .github/workflows/unit-tests.yml
name: Unit Tests
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - run: npm ci
      - run: npm run test:unit
      - run: npm run test:coverage
      
      - name: Upload coverage
        uses: codecov/codecov-action@v3
```

### 1. カバレッジ目標
- **行カバレッジ**: 80%以上
- **関数カバレッジ**: 90%以上
- **ブランチカバレッジ**: 75%以上

### 2. テスト優先順位
1. **High**: 認証・認可ロジック
2. **High**: API エンドポイント
3. **Medium**: UIコンポーネント
4. **Medium**: ユーティリティ関数
5. **Low**: 静的コンポーネント

### 3. Mock 戦略
- Supabase クライアント
- Next.js ルーター
- 外部API呼び出し

### 1. package.json スクリプト追加
```json
{
  "scripts": {
    "test": "jest",
    "test:unit": "jest --testPathPattern=__tests__/unit",
    "test:watch": "jest --watch",
    "test:coverage": "jest --coverage"
  }
}
```

### 2. Jest 設定
```javascript
// jest.config.js
module.exports = {
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  moduleNameMapping: {
    '^@/(.*)$': '<rootDir>/$1',
  },
  collectCoverageFrom: [
    'app/**/*.{js,jsx,ts,tsx}',
    'components/**/*.{js,jsx,ts,tsx}',
    'lib/**/*.{js,jsx,ts,tsx}',
    '\!**/*.d.ts',
  ],
};
```

### 3. テストファイル構造
```
__tests__/
├── unit/
│   ├── components/
│   │   ├── auth/
│   │   └── ui/
│   ├── lib/
│   └── api/
├── __mocks__/
│   ├── supabase.ts
│   └── next-router.ts
└── setup/
    └── jest.setup.js
```

## 関連ファイル
- `package.json` - 依存関係とスクリプト追加
- `jest.config.js` - Jest設定（新規作成）
- `jest.setup.js` - テストセットアップ（新規作成）
- `__tests__/` - テストディレクトリ（新規作成）
- `.github/workflows/unit-tests.yml` - GitHub Actions（新規作成）

## 依存関係
```json
{
  "devDependencies": {
    "@testing-library/react": "^14.0.0",
    "@testing-library/jest-dom": "^6.0.0",
    "@testing-library/user-event": "^14.0.0",
    "jest": "^29.0.0",
    "jest-environment-jsdom": "^29.0.0"
  }
}
```

## 優先度
High - コード品質とリグレッション防止のため

## 受け入れ条件
- [ ] Jest + React Testing Library が設定されている
- [ ] 主要コンポーネントのユニットテストが実装されている
- [ ] API エンドポイントのテストが実装されている
- [ ] GitHub Actions でテストが自動実行される
- [ ] カバレッジレポートが生成される
- [ ] PR時にテスト結果が表示される
- [ ] テストの実行時間が適切（5分以内）

## 注意点
- Supabase のモック設定
- Next.js App Router のテスト対応
- 認証状態のテストケース
- 非同期処理のテスト
