### ISSUE TITLE
機能テスト（Integration Tests）の実装とCI/CD統合

### ISSUE THREAD

**Issue by skage-plusfor** [plus4/plusfor-internal-portal#35]
## 概要
複数のコンポーネントやモジュールが連携する機能の動作を検証する機能テスト（Integration Tests）を実装し、GitHub Actions で自動実行できるようにします。

## 現在の問題
- コンポーネント間の連携テストが不足
- API とフロントエンドの統合テストがない
- データベースとの統合動作が未検証
- 機能全体の動作保証が不十分

#### 認証・認可機能
- **ログイン機能**: フォーム入力 → API呼び出し → 認証状態更新
- **ログアウト機能**: ログアウト → セッション削除 → リダイレクト
- **権限チェック**: ロール別アクセス制御の動作確認

#### ユーザー管理機能
- **ユーザー登録**: フォーム入力 → API → データベース保存 → 画面更新
- **ユーザー編集**: データ取得 → フォーム表示 → 更新 → 反映確認
- **ユーザー削除**: 削除実行 → データベース更新 → UI更新

#### お知らせ機能
- **お知らせ作成**: 作成フォーム → API → 保存 → 一覧反映
- **お知らせ表示**: データ取得 → 表示 → 既読更新
- **お知らせ管理**: 管理画面 → CRUD操作 → 状態管理

#### データベーステスト環境
- **Test Database**: Supabase テスト用プロジェクト
- **データ初期化**: 各テスト実行前のクリーンアップ
- **テストデータ**: 固定のテストユーザー・データ

#### API テスト環境
- **Next.js テストサーバー**: テスト専用環境
- **Mock外部API**: 必要に応じて外部サービスのMock
- **環境変数管理**: テスト用の環境変数設定

### 3. GitHub Actions ワークフロー
```yaml
# .github/workflows/integration-tests.yml
name: Integration Tests
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - run: npm ci
      - run: npm run db:test:setup
      - run: npm run test:integration
      
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_TEST_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_TEST_ANON_KEY }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_TEST_SERVICE_KEY }}
```

### 1. メインフレームワーク
- **Jest**: テストランナー
- **React Testing Library**: コンポーネントテスト
- **MSW (Mock Service Worker)**: API Mock（必要に応じて）

### 2. データベーステスト
- **@supabase/supabase-js**: テスト用クライアント
- **テストヘルパー**: データベース初期化・クリーンアップ

### 3. テストユーティリティ
```typescript
// __tests__/helpers/test-utils.tsx
export const renderWithProviders = (ui: React.ReactElement) => {
  return render(ui, {
    wrapper: ({ children }) => (
      <AuthProvider>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </AuthProvider>
    ),
  });
};

// __tests__/helpers/db-helpers.ts
export const setupTestDatabase = async () => {
  // テストデータの初期化
};

export const cleanupTestDatabase = async () => {
  // テストデータのクリーンアップ
};
```

### 1. package.json スクリプト
```json
{
  "scripts": {
    "test:integration": "jest --testPathPattern=__tests__/integration",
    "test:integration:watch": "jest --testPathPattern=__tests__/integration --watch",
    "db:test:setup": "node scripts/setup-test-db.js"
  }
}
```

### 2. テストファイル構造
```
__tests__/
├── integration/
│   ├── auth/
│   │   ├── login.test.tsx
│   │   └── signup.test.tsx
│   ├── admin/
│   │   ├── user-management.test.tsx
│   │   └── announcement-management.test.tsx
│   └── user/
│       ├── dashboard.test.tsx
│       └── profile.test.tsx
├── helpers/
│   ├── test-utils.tsx
│   ├── db-helpers.ts
│   └── auth-helpers.ts
└── fixtures/
    ├── users.json
    └── announcements.json
```

### 3. テスト例
```typescript
// __tests__/integration/admin/user-management.test.tsx
describe('ユーザー管理機能', () => {
  beforeEach(async () => {
    await cleanupTestDatabase();
    await setupTestDatabase();
  });

  test('新規ユーザー登録フロー', async () => {
    // 1. 管理者でログイン
    await loginAsAdmin();
    
    // 2. ユーザー管理ページに移動
    // 3. 新規ユーザーフォーム入力
    // 4. 登録実行
    // 5. データベース確認
    // 6. UI更新確認
  });
});
```

### 1. テスト分類
- **Happy Path**: 正常系のフロー
- **Error Handling**: エラーケースの処理
- **Authorization**: 権限チェック
- **Data Validation**: データ検証

### 2. テストデータ管理
- **固定テストデータ**: 予測可能なテストデータ
- **データ隔離**: テスト間のデータ競合回避
- **クリーンアップ**: 各テスト後のデータリセット

## 関連ファイル
- `__tests__/integration/` - 機能テストディレクトリ（新規作成）
- `__tests__/helpers/` - テストヘルパー（新規作成）
- `scripts/setup-test-db.js` - テストDB初期化スクリプト（新規作成）
- `.github/workflows/integration-tests.yml` - GitHub Actions（新規作成）

## 依存関係
```json
{
  "devDependencies": {
    "@testing-library/react": "^14.0.0",
    "@testing-library/user-event": "^14.0.0",
    "msw": "^2.0.0"
  }
}
```

## 関連Issue
- Issue #34: ユニットテスト実装（基盤となるテスト環境）
- 実装される各機能のIssue（テスト対象機能）

## 優先度
High - 機能の統合動作保証のため

## 受け入れ条件
- [ ] 主要機能の統合テストが実装されている
- [ ] テスト用データベース環境が構築されている
- [ ] GitHub Actions で統合テストが自動実行される
- [ ] テストデータの初期化・クリーンアップが自動化されている
- [ ] 認証・認可のテストが網羅されている
- [ ] エラーケースのテストが含まれている
- [ ] テスト実行時間が適切（10分以内）

## 注意点
- テスト用Supabaseプロジェクトの準備
- 本番データとの完全分離
- テスト実行時のリソース使用量
- 並列実行時のデータ競合対策
