### ISSUE TITLE
E2Eテストの実装とCI/CD統合

### ISSUE THREAD

**Issue by skage-plusfor** [plus4/plusfor-internal-portal#36]
## 概要
実際のブラウザ環境でユーザーの操作フローを再現するE2E（End-to-End）テストを実装し、GitHub Actions で自動実行できるようにします。リグレッションテストの最終段階として、本番環境に近い条件でのテストを行います。

## 現在の問題
- ユーザーの実際の操作フローが未検証
- ブラウザ環境での動作確認が手動のみ
- リリース前の総合的な動作確認が不十分
- クロスブラウザ対応の検証が困難

### 1. E2Eテストフレームワーク選定
- **Playwright** を採用（クロスブラウザ対応、高速、安定性）
- TypeScript サポート
- スクリーンショット・動画記録機能

#### 認証フロー
- **ログイン**: ログインページ → 認証情報入力 → ダッシュボード遷移
- **ログアウト**: ログアウト実行 → ログインページリダイレクト
- **パスワードリセット**: パスワードリセット → メール確認 → 新パスワード設定

#### 管理者機能
- **ユーザー管理**: ログイン → ユーザー管理 → 新規作成 → 編集 → 削除
- **お知らせ管理**: お知らせ作成 → 公開 → 編集 → 削除
- **権限管理**: 管理者専用ページアクセス確認

#### 一般ユーザー機能
- **ダッシュボード**: ログイン → ダッシュボード表示 → 各種情報確認
- **プロフィール**: プロフィール編集 → 保存 → 反映確認
- **お知らせ**: お知らせ一覧 → 詳細表示 → 既読更新

#### レスポンシブ対応
- **デスクトップ**: 1920x1080 での動作確認  
- **タブレット**: 768x1024 での動作確認
- **モバイル**: 375x667 での動作確認

### 3. GitHub Actions ワークフロー
```yaml
# .github/workflows/e2e-tests.yml
name: E2E Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # 毎日2時に実行

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npm run build
      - run: npm run test:e2e
      
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
      
      env:
        PLAYWRIGHT_TEST_BASE_URL: http://localhost:3000
        SUPABASE_URL: ${{ secrets.SUPABASE_TEST_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_TEST_ANON_KEY }}
```

### 4. クロスブラウザテスト
- **Chromium**: メインブラウザ
- **Firefox**: セカンダリブラウザ
- **Safari (WebKit)**: Safari互換性確認

### 1. Playwright設定
```typescript
// playwright.config.ts
import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './e2e',
  fullyParallel: true,
  forbidOnly: \!\!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  
  use: {
    baseURL: 'http://localhost:3000',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
    {
      name: 'mobile-chrome',
      use: { ...devices['Pixel 7'] },
    },
  ],

  webServer: {
    command: 'npm run start',
    url: 'http://localhost:3000',
    reuseExistingServer: \!process.env.CI,
  },
});
```

### 2. package.json スクリプト
```json
{
  "scripts": {
    "test:e2e": "playwright test",
    "test:e2e:ui": "playwright test --ui",
    "test:e2e:headed": "playwright test --headed",
    "test:e2e:debug": "playwright test --debug"
  }
}
```

### 3. テストファイル構造
```
e2e/
├── auth/
│   ├── login.spec.ts
│   ├── logout.spec.ts
│   └── password-reset.spec.ts
├── admin/
│   ├── user-management.spec.ts
│   ├── announcement-management.spec.ts
│   └── admin-dashboard.spec.ts
├── user/
│   ├── dashboard.spec.ts
│   ├── profile.spec.ts
│   └── announcements.spec.ts
├── responsive/
│   ├── mobile.spec.ts
│   └── tablet.spec.ts
├── fixtures/
│   ├── test-users.json
│   └── test-data.json
└── utils/
    ├── auth-helpers.ts
    ├── page-objects/
    │   ├── login-page.ts
    │   ├── dashboard-page.ts
    │   └── admin-page.ts
    └── test-helpers.ts
```

### 4. Page Object パターン実装
```typescript
// e2e/utils/page-objects/login-page.ts
export class LoginPage {
  constructor(private page: Page) {}

  async goto() {
    await this.page.goto('/auth/login');
  }

  async login(email: string, password: string) {
    await this.page.fill('[data-testid=email-input]', email);
    await this.page.fill('[data-testid=password-input]', password);
    await this.page.click('[data-testid=login-button]');
  }

  async expectLoginSuccess() {
    await expect(this.page).toHaveURL('/dashboard');
  }
}
```

### 5. テスト例
```typescript
// e2e/admin/user-management.spec.ts
import { test, expect } from '@playwright/test';
import { LoginPage } from '../utils/page-objects/login-page';
import { AdminPage } from '../utils/page-objects/admin-page';

test.describe('管理者ユーザー管理', () => {
  test('新規ユーザー作成フロー', async ({ page }) => {
    const loginPage = new LoginPage(page);
    const adminPage = new AdminPage(page);

    // 管理者でログイン
    await loginPage.goto();
    await loginPage.login('admin@test.com', 'password');
    
    // ユーザー管理ページに移動
    await page.click('[data-testid=admin-menu]');
    await page.click('[data-testid=user-management-link]');
    
    // 新規ユーザー作成
    await page.click('[data-testid=add-user-button]');
    await page.fill('[data-testid=user-name]', 'テストユーザー');
    await page.fill('[data-testid=user-email]', 'test@example.com');
    await page.click('[data-testid=save-button]');
    
    // 作成確認
    await expect(page.locator('[data-testid=success-message]')).toBeVisible();
    await expect(page.locator('text=テストユーザー')).toBeVisible();
  });
});
```

### 1. テスト優先度
- **Critical Path**: ログイン、主要機能（ユーザー管理、お知らせ）
- **High**: 管理者機能、権限チェック
- **Medium**: プロフィール編集、設定変更
- **Low**: 静的ページ、装飾的な機能

### 2. テストデータ管理
- **固定テストユーザー**: 管理者・一般ユーザー
- **テストデータ**: クリーンな状態から開始
- **データクリーンアップ**: テスト後の状態リセット

### 3. 並列実行対応
- テスト間のデータ競合回避
- 独立したテストユーザー使用
- 適切なテスト分離

## 関連ファイル
- `playwright.config.ts` - Playwright設定（新規作成）
- `e2e/` - E2Eテストディレクトリ（新規作成）
- `.github/workflows/e2e-tests.yml` - GitHub Actions（新規作成）
- `package.json` - スクリプトと依存関係追加

## 依存関係
```json
{
  "devDependencies": {
    "@playwright/test": "^1.40.0"
  }
}
```

## 関連Issue
- Issue #34: ユニットテスト実装
- Issue #35: 機能テスト実装
- 各機能実装Issue（テスト対象機能）

## 優先度
Medium - リリース前の品質保証のため

## 受け入れ条件
- [ ] Playwright が正しく設定されている
- [ ] 主要ユーザーフローのE2Eテストが実装されている
- [ ] クロスブラウザテストが実行される
- [ ] レスポンシブ対応のテストが含まれている
- [ ] GitHub Actions でE2Eテストが自動実行される
- [ ] テスト失敗時のスクリーンショット・動画が保存される
- [ ] Page Object パターンが適用されている
- [ ] テスト実行時間が適切（15分以内）

## 注意点
- テスト環境の安定性確保
- テストデータの適切な管理
- CI/CD環境でのブラウザリソース制限
- 外部依存関係（Supabase）の考慮
- テスト実行時間の最適化
