### ISSUE TITLE
Tailwind CSS v4へのアップグレード

### ISSUE THREAD

**Issue by skage-plusfor** [plus4/plusfor-internal-portal#40]
## 概要
現在のTailwind CSS v3.4.1を最新のv4にアップグレードします。コンポーネントが増える前の今が最適なタイミングです。新機能の活用とパフォーマンス向上、将来のメンテナンス性を向上させます。

## 現在の状況
```json
// package.json (現在)
"tailwindcss": "^3.4.1"
```

### 1. パフォーマンス向上
- **新しいエンジン**: Rust製の高速コンパイラ
- **ビルド時間短縮**: 大幅な高速化
- **バンドルサイズ削減**: 不要なCSSの削除改善

### 2. 新機能
- **@import** サポートの改善
- **カスタムプロパティ**: CSS変数の統合強化
- **Container Queries**: コンテナクエリのネイティブサポート
- **View Transitions**: ページ遷移アニメーション
- **Modern CSS**: Grid subgrid、:has() セレクタなど

### 3. 開発体験の向上
- **TypeScript**: より良いTypeScript統合
- **IntelliSense**: VS Code拡張の改善
- **デバッグ**: 開発ツールの強化

#### 依存関係の確認
```bash
npm list tailwindcss
npm outdated tailwindcss
```

#### 現在の設定ファイル確認
- `tailwind.config.ts`
- `postcss.config.mjs`
- `globals.css`

#### Step 1: パッケージ更新
```bash
# Tailwind CSS v4 のインストール
npm install tailwindcss@next @tailwindcss/typography@next

# 関連パッケージも最新版に
npm install autoprefixer@next postcss@next
```

#### Step 2: 設定ファイル移行
```typescript
// tailwind.config.ts (v4対応)
import type { Config } from "tailwindcss";

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      // v4の新機能を活用
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        // CSS変数の活用強化
      },
      // Container queries 対応
      containers: {
        xs: "20rem",
        sm: "24rem",
        md: "28rem",
        lg: "32rem",
        xl: "36rem",
      },
    },
  },
  plugins: [
    // v4対応プラグイン
  ],
} satisfies Config;
```

#### Step 3: CSS ファイル更新
```css
/* app/globals.css */
@import "tailwindcss";

/* v4の新しい@import記法 */
@config "./tailwind.config.ts";

/* CSS変数の定義強化 */
:root {
  --background: 0 0% 100%;
  --foreground: 222.2 84% 4.9%;
  /* ... 他のCSS変数 */
}

@media (prefers-color-scheme: dark) {
  :root {
    --background: 222.2 84% 4.9%;
    --foreground: 210 40% 98%;
    /* ... ダークモード対応 */
  }
}
```

#### 既存コンポーネントのテスト
```bash
# shadcn/ui コンポーネントの動作確認
npm run dev
```

#### 必要に応じてshadcn/ui更新
```bash
# shadcn/uiが最新のTailwind v4に対応している場合
npx shadcn-ui@latest init --force
```

#### Container Queries の導入
```typescript
// components/responsive-component.tsx
<div className="@container">
  <div className="@md:grid-cols-2 @lg:grid-cols-3">
    {/* レスポンシブグリッド */}
  </div>
</div>
```

#### View Transitions API
```css
/* globals.css */
@view-transition {
  navigation: auto;
}

.page-transition {
  view-transition-name: main-content;
}
```

### 1. 削除された機能
- 一部の非推奨クラスの削除確認
- プラグインAPIの変更対応

### 2. 設定変更
```typescript
// 設定ファイルの調整が必要な場合
export default {
  // v3からv4への移行設定
  future: {
    // 新機能の段階的有効化
  },
  experimental: {
    // 実験的機能のテスト
  },
} satisfies Config;
```

### 1. 視覚的回帰テスト
- 既存ページのスクリーンショット比較
- 主要コンポーネントの表示確認
- ダークモード/ライトモードの確認

### 2. 機能テスト
- レスポンシブデザインの確認
- アニメーション/トランジションの動作
- ビルドプロセスの確認

### 3. パフォーマンステスト
```bash
# ビルド時間の測定
time npm run build

# バンドルサイズの確認
npm run build && npx @next/bundle-analyzer
```

### 1. バックアップ
```bash
# 現在の設定をバックアップ
cp tailwind.config.ts tailwind.config.ts.backup
cp package.json package.json.backup
```

### 2. ロールバック手順
```bash
# 問題が発生した場合
npm install tailwindcss@^3.4.1
# 設定ファイルを復元
```

## 実装順序
1. **事前調査**: v4の変更点とプロジェクトへの影響確認
2. **開発環境**: 開発環境でのアップグレードとテスト
3. **設定調整**: 新機能の活用と最適化
4. **全体テスト**: 全ページ・コンポーネントの動作確認
5. **ステージング**: ステージング環境でのテスト
6. **本番適用**: 本番環境への適用

### 1. 即座の効果
- **ビルド時間短縮**: 開発体験の向上
- **バンドルサイズ削減**: パフォーマンス改善
- **開発効率**: 新しいユーティリティクラスの活用

### 2. 長期的効果
- **将来性**: 最新機能への対応
- **メンテナンス性**: 新しいアーキテクチャの恩恵
- **コミュニティサポート**: 最新版のサポート継続

## 関連ファイル
- `package.json` - 依存関係更新
- `tailwind.config.ts` - 設定ファイル更新
- `postcss.config.mjs` - PostCSS設定確認
- `app/globals.css` - CSS imports更新
- `components/ui/*` - shadcn/uiコンポーネント
- `.vscode/settings.json` - VS Code設定（必要に応じて）

## 関連Issue
- Issue #32: ファビコン・タイトル変更（デザイン統一）
- Issue #26: テーマ切り替え問題（CSS変数との連携強化）
- 今後のUI改善Issue（新機能活用）

## 優先度
Medium - 将来のメンテナンス性向上とパフォーマンス改善のため

## 受け入れ条件
- [ ] Tailwind CSS v4が正常にインストールされている
- [ ] 既存のすべてのページが正常に表示される
- [ ] shadcn/uiコンポーネントが正常に動作する
- [ ] ダークモード/ライトモードが正常に切り替わる
- [ ] ビルドプロセスが成功する
- [ ] レスポンシブデザインが維持されている
- [ ] パフォーマンスが向上または維持されている
- [ ] 新機能（可能な範囲で）が活用されている

## 注意点
- **破壊的変更**: v3からv4への移行時の互換性
- **shadcn/ui互換性**: UIライブラリとの相性確認
- **ビルドパイプライン**: CI/CDでのビルド確認
- **ブラウザサポート**: 新機能のブラウザ対応状況
- **チーム学習**: 新機能についての知識共有

### 1. 新機能の段階的導入
- Container Queries の適用箇所検討
- View Transitions の UX 改善活用

### 2. パフォーマンス最適化
- PurgeCSS の最適化
- Critical CSS の改善

### 3. 開発環境の強化
- VS Code 拡張の活用
- Tailwind CSS IntelliSense の設定最適化
